### PR TITLE
V3.0.0

### PR DESCRIPTION
**Pull request by theanilpaudel**

### CODE REVIEW

**Comment by negativetwelve** [comment]
@theanilpaudel @richardgroves thanks for making this PR - does it make more sense to just put a giant deprecation notice on this repo and point them to the new repo https://github.com/uxcam/react-native-ux-cam?

Also, if we change the package name to `react-native-uxcam`, you're going to need to get access to the npm package in order to publish it.

**Comment by theanilpaudel** [comment]
@negativetwelve Yes, I think it makes more sense to put a giant deprecation notice on your repo and point it towards [https://github.com/uxcam/react-native-ux-cam](url)

We are planning to publish this on the same npm that you are using i.e react-native-ux-cam (there was a typo on the installation instructions and I pushed a commit for that) so we might as well need access to your npm repository [https://www.npmjs.com/package/react-native-ux-cam](url); so as to not poke you time and again :smiley:

**Comment by richardgroves** [comment]
Let’s run on this repo for a bit to get the migration to v3 underway, then can move over once it is all ok.

**Comment by negativetwelve** [comment]
sounds good to me @richardgroves

**Pull request merged**
