### PR TITLE
Fix 'Argument list too long' error

### PR DESCRIPTION
**Pull request by sairus2k**
Resolve the issue #51

### CODE REVIEW

**Comment by negativetwelve** [comment]
This looks great, thanks for the contribution. I'll merge and do a release after I test this!

**Comment by sairus2k** [comment]
https://github.com/CocoaPods/CocoaPods/issues/7765
The related issue for the travis-ci test failing.

**Comment by sairus2k** [comment]
@negativetwelve could you please test the PR? This is the very annoying issue. After each update of node_modules, I need to edit FRAMEWORK_SEARCH_PATHS to compile a project.

**Comment by negativetwelve** [comment]
I'd like to find and fix the issue that's failing in the tests. I'll look into this now.

**Comment by negativetwelve** [comment]
@sairus2k thanks again for posting this, I fixed the CI issues in this branch https://github.com/negativetwelve/react-native-ux-cam/pull/60 - can you merge master into this and then we can merge? I'll make a release right after as well. Sorry for the issues with the package!

**Comment by sairus2k** [comment]
@negativetwelve circle-ci is happy now!

**Comment by negativetwelve** [comment]
awesome! merging and I'll do a release now as well

**Comment by negativetwelve** [comment]
Published as 4.5.0 - https://www.npmjs.com/package/react-native-ux-cam - please let me know if you run into any issues and also thank you for pushing this fix cross the finish line!

**Pull request merged**
